name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  gh-pages-deploy:
    name: Deploying to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js for use with actions
        uses: actions/setup-node@v2-beta
        with:
          version: 16.14.0
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Clean install dependencies
        run: |
          if [ -e yarn.lock ]; then
          yarn install --frozen-lockfile
          elif [ -e package-lock.json ]; then
          npm ci
          else
          npm i
          fi

      - name: Build Application
        run: npx ember build --environment=production

      - name: Run deploy script
        run: sh ./scripts/gh-pages-deploy.sh
